name: JFrog Docker Scan Workflow

on:
  push:
    branches:
      - main

jobs:
  jfrog-docker-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v1
      with:
        version: '2.77.0'

    

    - name: Configure JFrog CLI
      run: |
        jfrog config add my-artifactory --url "xxx" --user "sss" --password "xxx" --interactive=false

    - name: Pull Docker image
      run: |
        docker pull nginx:latest
        jfrog rt dp nginx:latest sss-docker-local --build-name=check --build-number=3
        jfrog rt build-publish check 3
        jfrog bs check 3

    # - name: Perform JFrog Docker scan
    #   run: |
    #     jfrog docker scan nginx:latest \
    #     --watches "failbuild" \
    #     --fail=false
          
